version: '3.8'

services:
  tokenizer:
    container_name: tokenizer
    hostname: tokenizer
    build:
      context: .
      dockerfile: ./src/Tokenizer/Dockerfile
    ports:
      - "5283:8080"
    networks:
      - app-network
  
  rg:
    container_name: rg
    hostname: rg
    build:
      context: .
      dockerfile: ./src/RemittanceGateway/Dockerfile
    ports:
      - "5250:8080"
    networks:
      - app-network
        
  rest-adapter:
    container_name: rest-adapter
    hostname: rest-adapter
    build:
      context: .
      dockerfile: ./src/RestAdapter/Dockerfile
    ports:
      - "5047:8080"
    networks:
      - app-network

  rest-provider:
    container_name: rest-provider
    hostname: rest-provider
    build:
      context: .
      dockerfile: ./src/RestProvider/Dockerfile
    ports:
      - "5196:8080"
    networks:
      - app-network

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: ./src/proxy/Dockerfile
    ports:
      - "8080:80"   # Expose Nginx on port 8080
      - "8081:8081"
    depends_on:
      - rg
      - rest-provider
      - tokenizer
      - rest-adapter
    networks:
      - app-network
    volumes:
      - ./src/proxy/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./src/proxy/lua/.:/usr/local/openresty/nginx/conf/lua/.
      - ./nginx/log:/var/log/nginx

networks:
  app-network:
    driver: bridge
    name: sandbox_net